WebApplication1/Pages/Application/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service;
using WebApplication1.Model;

namespace WebApplication1.Pages.Application
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public Student studentModel { get; set; }
        private IStudentLogic _studentLogic;

        public EditModel(IStudentLogic studentLogic)
        {
            _studentLogic = studentLogic;
        }

        public async Task OnGetAsync()
        {
            Guid id = new Guid(Request.Query["id"]);
            studentModel =  await _studentLogic.GetStudentAsync(id);
        }

        public IActionResult OnPostUpdateApplication()
        {
            //Todo: update logic
            return RedirectToPage("./Overview");
        }

        public IActionResult OnPostBack()
        {
            return RedirectToPage("./Overview");
        }
    }
}

WebApplication1/Pages/Application/Overview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using WebApplication1.Model;

namespace WebApplication1.Pages.Application
{
    public class OverviewModel : PageModel
    {
        public IList<Student> students { get; set; }
        public string url { get; set; }
        public async Task OnGetAsync()
        {
            url = "https://localhost:44339/odata/odataApplication";
        }
    }
}

WebApplication1/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication1.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

WebApplication1/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication1.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

WebApplication1/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace WebApplication1.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

WebApplication1/Pages/Students/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Service;
using WebApplication1.Model;

namespace WebApplication1.Pages.Students
{
    public class EditModel : PageModel
    {
        [BindProperty]
        public Student studentModel { get; set; }
        private IStudentLogic _studentLogic;

        public EditModel(IStudentLogic studentLogic)
        {
            _studentLogic = studentLogic;
        }

        public async Task OnGetAsync()
        {
            Guid id = new Guid(Request.Query["id"]);
            studentModel =  await _studentLogic.GetStudentAsync(id);
        }

        public IActionResult OnPostUpdateApplication()
        {
            //Todo: update logic
            return RedirectToPage("./Overview");
        }

        public IActionResult OnPostBack()
        {
            return RedirectToPage("./Overview");
        }
    }
}

WebApplication1/Pages/Students/Overview.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using WebApplication1.Model;

namespace WebApplication1.Pages.Students
{
    public class OverviewModel : PageModel
    {
        public IList<Student> students { get; set; }
        public string url { get; set; }
        public async Task OnGetAsync()
        {
            url = "https://localhost:44372/odata/Students";
            //url = "https://localhost:44339/odata/odataApplication";
            //students = await GetDummyServiceAsync();
        }
    }
}

WebApplication1/Pages/Application/Edit.cshtml
@page  
@model WebApplication1.Pages.Application.EditModel
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label> Id</label>
        <input type="text" class="form-control col-md-3" asp-for="studentModel.Id" readonly="readonly" contenteditable="false" />
    </div>
    <div class="form-group">
        <label> Title</label>
        <input type="text" class="form-control col-md-3" asp-for="studentModel.Name" />
        <span asp-validation-for="studentModel.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label> Title</label>
        <input type="text" class="form-control col-md-3" asp-for="studentModel.Score" />
        <span asp-validation-for="studentModel.Score" class="text-danger"></span>
    </div>

    <div>
        <button type="submit" asp-page-handler="UpdateApplication">Save</button>
        <button type="submit" asp-page-handler="Back">Back</button>
    </div>
</form>

WebApplication1/Pages/Application/Overview.cshtml
@page
@model WebApplication1.Pages.Application.OverviewModel
@{
    ViewData["Title"] = "Overview";
}

<h1>Overview</h1>

@section Styles{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css" />
}

<form method="post">
    <div style="width:95vw">
                
        <div class="table-responsive">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-hover" id="applicationOverview">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</form>


@section Scripts {
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $('#applicationOverview').dataTable({
                "sPaginationType": "numbers",
                "aLengthMenu": [[10, 20, 50, -1], ["10", "20", "50", "All"]],
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "@Model.url",
                "aoColumns": [
                    {
                        "mData": "Id",
                        "sType": "guid"
                    },
                    { "mData": "Title" },
                     null 
                ],
                "columnDefs": [
                    {
                        "targets": [2],
                        "bSearchable": false,
                        "bSortable": false,
                        "mRender": function (data, type, row, meta) {
                            return "<div><a href='./Edit?id=" + row.Id +"'> Edit</a> | <button type='submit' asp-page-handler='Delete' asp-route-id='" + row.Id + "' style='border: none' class='link' onclick='return confirm(\" Delete " + row.Id +" ? \");' > Delete</button></div> ";
                        }
                    }
                ],
                "fnServerData": fnServerOData,
                "iODataVersion": 4,
                "bUseODataViaJSONP": false // set to true if using cross-domain requests ; set to false due to backend implemented CROS.
            });
        });
    </script>
}

WebApplication1/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebApplication1/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/NavooStyleSheet.css" />
    @RenderSection("Styles", false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Students/Overview">Student</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Application/Overview">Application</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main" class="pb-3">
            <div style="margin-left:30px">
                @RenderBody()
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - WebApplication1 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/jquery-datatables-odata/media/js/jquery.js"></script>
    <script src="~/jquery-datatables-odata/media/js/jquery.dataTables.js"></script>
    <script src="~/jquery-datatables-odata/media/js/jquery.dataTables.odata.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication1/Pages/Students/Edit.cshtml
@page  
@model WebApplication1.Pages.Students.EditModel
@{
    ViewData["Title"] = "Edit";
}

<form method="post">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label> Id</label>
        <input type="text" class="form-control col-md-3" asp-for="studentModel.Id" readonly="readonly" contenteditable="false" />
    </div>
    <div class="form-group">
        <label> Title</label>
        <input type="text" class="form-control col-md-3" asp-for="studentModel.Name" />
        <span asp-validation-for="studentModel.Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label> Title</label>
        <input type="text" class="form-control col-md-3" asp-for="studentModel.Score" />
        <span asp-validation-for="studentModel.Score" class="text-danger"></span>
    </div>

    <div>
        <button type="submit" asp-page-handler="UpdateApplication">Save</button>
        <button type="submit" asp-page-handler="Back">Back</button>
    </div>
</form>

WebApplication1/Pages/Students/Overview.cshtml
@page
@model WebApplication1.Pages.Students.OverviewModel
@{
    ViewData["Title"] = "Overview";
}

<h1>Overview</h1>

@section Styles{
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.15/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css" />
}

<form method="post">
    <div style="width:95vw">
        @*<div class="table-responsive">
            <table class="table table-hover" id="example">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Score</th>
                        <th />
                    </tr>
                </thead>
                <tbody>
                    @if (@Model.students != null)
                    {
                        @foreach (var contact in @Model.students)
                        {
                            <tr>
                                <td> @contact.Id </td>
                                <td> @contact.Name</td>
                                <td> @contact.Score</td>                                
                            </tr>
                        }
                    }
                </tbody>
            </table>
        </div>*@
        
        <div class="table-responsive">
            <table cellpadding="0" cellspacing="0" border="0" class="table table-hover" id="applicationOverview">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </div>
</form>


@section Scripts {
    <script src="~/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap4.min.js"></script>
    <script>
        $(function () {
            $('#applicationOverview').dataTable({
                "sPaginationType": "numbers",
                "aLengthMenu": [[10, 20, 50, -1], ["10", "20", "50", "All"]],
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "@Model.url",
                "aoColumns": [
                    {
                        "mData": "Id",
                        "sType": "guid"
                    },
                    { "mData": "Name" },
                     null 
                ],
                "columnDefs": [
                    {
                        "targets": [2],
                        "bSearchable": false,
                        "bSortable": false,
                        "mRender": function (data, type, row, meta) {
                            return "<div><a href='./Edit?id=" + row.Id +"'> Edit</a> | <button type='submit' asp-page-handler='Delete' asp-route-id='" + row.Id + "' style='border: none' class='link' onclick='return confirm(\" Delete " + row.Id +" ? \");' > Delete</button></div> ";
                        }
                    }
                ],
                "fnServerData": fnServerOData,
                "iODataVersion": 4,
                "bUseODataViaJSONP": false // set to true if using cross-domain requests ; set to false due to backend implemented CROS.
            });
        });
    </script>
}